### ISSUE TITLE
how to calculate the height of tableviewcell by taglistview

### ISSUE THREAD

**Issue by hengchengfei** [xhacker/TagListView#42]
func tableView(tableView: UITableView, heightForRowAtIndexPath indexPath: NSIndexPath) -> CGFloat {

// how to get the height of taglistview
 ...
}

**Comment by xhacker** [comment]
Once you have set the width for TagListView, you can use `intrinsicContentSize()` to get its size.

Another way is to use Auto Layout and UITableViewAutomaticDimension.

**Comment by UberJason** [comment]
Using UITableViewAutomaticDimension seems a bit tricky since TagListView seems to require manually adding tags with calls to addTag(). (Correct me if I'm wrong on that one.) 

If you have a UITableViewCell subclass with a TagListView as a subview with constraints set up, the TagListView doesn't actually have any tags until you call addTag() a few times while configuring the cell (for example in cellForRowAtIndexPath). But by that point the table view has already calculated the height for that cell, so it doesn't render correctly. 

Forcing a tableView.reloadData() in viewDidAppear() fixes the height, but with a noticeable "flash" as the incorrect height is briefly shown, then corrected. I also tried calling TagListView.layoutIfNeeded() after adding tags, but that doesn't seem to do the trick. Any suggestions?

**Comment by hengchengfei** [comment]
I Use ScrollView

**Comment by ErAshu** [comment]
Any Success on this??

**Comment by Cee** [comment]
@ErAshu Er #178 should be useful
